<?php

use Illuminate\Database\Seeder;

class CategoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('categories')->delete();

        \DB::table('categories')->insert(array(
//            0 =>
//            array (
//                'category_id' => 2,
//                'category_name' => 'Fashion',
//                'parent_id' => NULL,
//                'brand' => 1,
//                'th_mime_type' => NULL,
//                'th_name' => 'Fashion',
//                'th_size' => 3,
//                'created_at' => '2018-09-21 02:00:00',
//                'updated_at' => '2018-09-21 00:00:00',
//                'created_by' => 0,
//                'updated_by' => 0,
//            ),
//            1 =>
//            array (
//                'category_id' => 3,
//                'category_name' => 'Furnitures',
//                'parent_id' => NULL,
//                'brand' => 2,
//                'th_mime_type' => NULL,
//                'th_name' => 'Furnitures',
//                'th_size' => 3,
//                'created_at' => '2018-09-21 02:00:00',
//                'updated_at' => '2018-09-21 00:00:00',
//                'created_by' => 0,
//                'updated_by' => 0,
//            ),
//            2 =>
//            array (
//                'category_id' => 4,
//                'category_name' => 'Jewelry & Watches',
//                'parent_id' => NULL,
//                'brand' => 1,
//                'th_mime_type' => NULL,
//                'th_name' => 'Jewelry & Watches',
//                'th_size' => 3,
//                'created_at' => '2018-09-21 02:00:00',
//                'updated_at' => '2018-09-21 00:00:00',
//                'created_by' => 0,
//                'updated_by' => 0,
//            ),
//            3 =>
//            array (
//                'category_id' => 5,
//                'category_name' => 'Electronics',
//                'parent_id' => NULL,
//                'brand' => 1,
//                'th_mime_type' => NULL,
//                'th_name' => 'Electronics',
//                'th_size' => 3,
//                'created_at' => NULL,
//                'updated_at' => NULL,
//                'created_by' => 0,
//                'updated_by' => 0,
//            ),
//            4 =>
//            array (
//                'category_id' => 6,
//                'category_name' => 'Men',
//                'parent_id' => 2,
//                'brand' => 1,
//                'th_mime_type' => NULL,
//                'th_name' => 'Men',
//                'th_size' => 3,
//                'created_at' => NULL,
//                'updated_at' => NULL,
//                'created_by' => 0,
//                'updated_by' => 0,
//            ),
//            5 =>
//            array (
//                'category_id' => 7,
//                'category_name' => 'Edition',
//                'parent_id' => NULL,
//                'brand' => 2,
//                'th_mime_type' => NULL,
//                'th_name' => 'Jewelry & Watches',
//                'th_size' => 3,
//                'created_at' => '2018-09-21 02:00:00',
//                'updated_at' => '2018-09-21 00:00:00',
//                'created_by' => 0,
//                'updated_by' => 0,
//            ),
//            6 =>
//            array (
//                'category_id' => 8,
//                'category_name' => 'Test Edition',
//                'parent_id' => NULL,
//                'brand' => 2,
//                'th_mime_type' => NULL,
//                'th_name' => 'Test Edition',
//                'th_size' => NULL,
//                'created_at' => '2018-09-21 02:00:00',
//                'updated_at' => '2018-09-21 00:00:00',
//                'created_by' => 0,
//                'updated_by' => 0,
//            ),
            0 =>
                array(
                    'category_id' => 1,
                    'category_name' => 'Advertising',
                    'parent_id' => NULL,
                    'brand' => 1,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            1 =>
                array(
                    'category_id' => 2,
                    'category_name' => 'Photo & Video Library',
                    'parent_id' => NULL,
                    'brand' => 1,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            2 =>
                array(
                    'category_id' => 3,
                    'category_name' => 'In-store Communication',
                    'parent_id' => NULL,
                    'brand' => 1,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            3 =>
                array(
                    'category_id' => 4,
                    'category_name' => 'Branding',
                    'parent_id' => 1,
                    'brand' => 1,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            4 =>
                array(
                    'category_id' => 5,
                    'category_name' => 'Traffic',
                    'parent_id' => 1,
                    'brand' => 1,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            5 =>
                array(
                    'category_id' => 6,
                    'category_name' => 'Technical Video',
                    'parent_id' => 3,
                    'brand' => 1,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            6 =>
                array(
                    'category_id' => 7,
                    'category_name' => 'Corporate Video',
                    'parent_id' => 3,
                    'brand' => 1,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            7 =>
                array(
                    'category_id' => 8,
                    'category_name' => 'Advertising',
                    'parent_id' => NULL,
                    'brand' => 2,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            8 =>
                array(
                    'category_id' => 9,
                    'category_name' => 'Photo & Video Library',
                    'parent_id' => NULL,
                    'brand' => 2,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            9 =>
                array(
                    'category_id' => 10,
                    'category_name' => 'In-store Communication',
                    'parent_id' => NULL,
                    'brand' => 2,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            10 =>
                array(
                    'category_id' => 11,
                    'category_name' => 'Branding',
                    'parent_id' => 8,
                    'brand' => 2,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            11 =>
                array(
                    'category_id' => 12,
                    'category_name' => 'Traffic',
                    'parent_id' => 8,
                    'brand' => 2,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            12 =>
                array(
                    'category_id' => 13,
                    'category_name' => 'Photo',
                    'parent_id' => 9,
                    'brand' => 2,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            13 =>
                array(
                    'category_id' => 14,
                    'category_name' => 'Video',
                    'parent_id' => 9,
                    'brand' => 2,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            14 =>
                array(
                    'category_id' => 15,
                    'category_name' => 'Flyer',
                    'parent_id' => 10,
                    'brand' => 2,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            15 =>
                array(
                    'category_id' => 16,
                    'category_name' => 'Product Brochure',
                    'parent_id' => 10,
                    'brand' => 2,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            16 =>
                array(
                    'category_id' => 17,
                    'category_name' => 'New Collection',
                    'parent_id' => 5,
                    'brand' => 1,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            17 =>
                array(
                    'category_id' => 18,
                    'category_name' => 'Sale',
                    'parent_id' => 5,
                    'brand' => 1,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            18 =>
                array(
                    'category_id' => 19,
                    'category_name' => 'New Collection',
                    'parent_id' => 12,
                    'brand' => 2,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            19 =>
                array(
                    'category_id' => 20,
                    'category_name' => 'Sale',
                    'parent_id' => 12,
                    'brand' => 2,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            20 =>
                array(
                    'category_id' => 21,
                    'category_name' => 'Comfort Days',
                    'parent_id' => 12,
                    'brand' => 2,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
//            21 =>
//                array(
//                    'category_id' => 22,
//                    'category_name' => 'Technical',
//                    'parent_id' => 14,
//                    'brand' => 2,
//                    'th_mime_type' => NULL,
//                    'th_name' => 'category.jpeg',
//                    'th_size' => NULL,
//                    'created_at' => '2018-09-21 02:00:00',
//                    'updated_at' => '2018-09-21 00:00:00',
//                    'created_by' => 0,
//                    'updated_by' => 0,
//                ),
            22 =>
                array(
                    'category_id' => 23,
                    'category_name' => 'Print',
                    'parent_id' => 17,
                    'brand' => 1,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            23 =>
                array(
                    'category_id' => 24,
                    'category_name' => 'Ooh',
                    'parent_id' => 17,
                    'brand' => 1,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            24 =>
                array(
                    'category_id' => 25,
                    'category_name' => 'Pop',
                    'parent_id' => 17,
                    'brand' => 1,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),

            25 =>
                array(
                    'category_id' => 26,
                    'category_name' => 'Video',
                    'parent_id' => 17,
                    'brand' => 1,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            26 =>
                array(
                    'category_id' => 27,
                    'category_name' => 'Radio',
                    'parent_id' => 17,
                    'brand' => 1,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            27 =>
                array(
                    'category_id' => 28,
                    'category_name' => 'Print',
                    'parent_id' => 18,
                    'brand' => 1,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            28 =>
                array(
                    'category_id' => 29,
                    'category_name' => 'Ooh',
                    'parent_id' => 18,
                    'brand' => 1,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            29 =>
                array(
                    'category_id' => 30,
                    'category_name' => 'Pop',
                    'parent_id' => 18,
                    'brand' => 1,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),

            30 =>
                array(
                    'category_id' => 31,
                    'category_name' => 'Video',
                    'parent_id' => 18,
                    'brand' => 1,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            31 =>
                array(
                    'category_id' => 32,
                    'category_name' => 'Radio',
                    'parent_id' => 18,
                    'brand' => 1,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            32 =>
                array(
                    'category_id' => 33,
                    'category_name' => 'Print',
                    'parent_id' => 11,
                    'brand' => 2,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            33 =>
                array(
                    'category_id' => 34,
                    'category_name' => 'Ooh',
                    'parent_id' => 11,
                    'brand' => 2,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            34 =>
                array(
                    'category_id' => 35,
                    'category_name' => 'Pop',
                    'parent_id' => 11,
                    'brand' => 2,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),

            35 =>
                array(
                    'category_id' => 36,
                    'category_name' => 'Video',
                    'parent_id' => 11,
                    'brand' => 2,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            36 =>
                array(
                    'category_id' => 37,
                    'category_name' => 'Radio',
                    'parent_id' => 11,
                    'brand' => 2,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            37 =>
                array(
                    'category_id' => 38,
                    'category_name' => 'Print',
                    'parent_id' => 21,
                    'brand' => 2,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            38 =>
                array(
                    'category_id' => 39,
                    'category_name' => 'Ooh',
                    'parent_id' => 21,
                    'brand' => 2,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            39 =>
                array(
                    'category_id' => 40,
                    'category_name' => 'Pop',
                    'parent_id' => 21,
                    'brand' => 2,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),

            40 =>
                array(
                    'category_id' => 41,
                    'category_name' => 'Video',
                    'parent_id' => 21,
                    'brand' => 2,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            41 =>
                array(
                    'category_id' => 42,
                    'category_name' => 'Radio',
                    'parent_id' => 21,
                    'brand' => 2,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            42 =>
                array(
                    'category_id' => 43,
                    'category_name' => 'Print',
                    'parent_id' => 19,
                    'brand' => 2,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            43 =>
                array(
                    'category_id' => 44,
                    'category_name' => 'Ooh',
                    'parent_id' => 19,
                    'brand' => 2,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            44 =>
                array(
                    'category_id' => 45,
                    'category_name' => 'Pop',
                    'parent_id' => 19,
                    'brand' => 2,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),

            45 =>
                array(
                    'category_id' => 46,
                    'category_name' => 'Video',
                    'parent_id' => 19,
                    'brand' => 2,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            46 =>
                array(
                    'category_id' => 47,
                    'category_name' => 'Radio',
                    'parent_id' => 19,
                    'brand' => 2,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            47 =>
                array(
                    'category_id' => 48,
                    'category_name' => 'Print',
                    'parent_id' => 20,
                    'brand' => 2,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            48 =>
                array(
                    'category_id' => 49,
                    'category_name' => 'Ooh',
                    'parent_id' => 20,
                    'brand' => 2,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            49 =>
                array(
                    'category_id' => 50,
                    'category_name' => 'Pop',
                    'parent_id' => 20,
                    'brand' => 2,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),

            50 =>
                array(
                    'category_id' => 51,
                    'category_name' => 'Video',
                    'parent_id' => 20,
                    'brand' => 2,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            51 =>
                array(
                    'category_id' => 52,
                    'category_name' => 'Radio',
                    'parent_id' => 20,
                    'brand' => 2,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            52 =>
                array(
                    'category_id' => 53,
                    'category_name' => 'Philo',
                    'parent_id' => 4,
                    'brand' => 1,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            53 =>
                array(
                    'category_id' => 54,
                    'category_name' => 'Jeremy',
                    'parent_id' => 4,
                    'brand' => 1,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            54 =>
                array(
                    'category_id' => 55,
                    'category_name' => 'Ido',
                    'parent_id' => 4,
                    'brand' => 1,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            55 =>
                array(
                    'category_id' => 56,
                    'category_name' => 'La Scala',
                    'parent_id' => 4,
                    'brand' => 1,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            56 =>
                array(
                    'category_id' => 57,
                    'category_name' => 'Herman',
                    'parent_id' => 4,
                    'brand' => 1,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            57 =>
                array(
                    'category_id' => 58,
                    'category_name' => 'Print',
                    'parent_id' => 53,
                    'brand' => 1,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            58 =>
                array(
                    'category_id' => 59,
                    'category_name' => 'Print',
                    'parent_id' => 54,
                    'brand' => 1,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            59 =>
                array(
                    'category_id' => 60,
                    'category_name' => 'Print',
                    'parent_id' => 55,
                    'brand' => 1,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            60 =>
                array(
                    'category_id' => 61,
                    'category_name' => 'Print',
                    'parent_id' => 56,
                    'brand' => 1,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            61 =>
                array(
                    'category_id' => 62,
                    'category_name' => 'Print',
                    'parent_id' => 57,
                    'brand' => 1,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            62 =>
                array(
                    'category_id' => 63,
                    'category_name' => 'Social Contents',
                    'parent_id' => NULL,
                    'brand' => 1,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            63 =>
                array(
                    'category_id' => 64,
                    'category_name' => 'Branding',
                    'parent_id' => 63,
                    'brand' => 1,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            64 =>
                array(
                    'category_id' => 65,
                    'category_name' => 'Events',
                    'parent_id' => 63,
                    'brand' => 1,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            65 =>
                array(
                    'category_id' => 66,
                    'category_name' => 'Social Contents',
                    'parent_id' => NULL,
                    'brand' => 2,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            66 =>
                array(
                    'category_id' => 67,
                    'category_name' => 'Branding',
                    'parent_id' => 66,
                    'brand' => 2,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            67 =>
                array(
                    'category_id' => 68,
                    'category_name' => 'Events',
                    'parent_id' => 66,
                    'brand' => 2,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            68 =>
                array(
                    'category_id' => 69,
                    'category_name' => 'Social',
                    'parent_id' => 21,
                    'brand' => 2,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
            69 =>
                array(
                    'category_id' => 70,
                    'category_name' => 'Social',
                    'parent_id' => 17,
                    'brand' => 1,
                    'th_mime_type' => NULL,
                    'th_name' => 'category.jpeg',
                    'th_size' => NULL,
                    'created_at' => '2018-09-21 02:00:00',
                    'updated_at' => '2018-09-21 00:00:00',
                    'created_by' => 0,
                    'updated_by' => 0,
                ),
        ));


    }
}