<?php

use Illuminate\Database\Seeder;

class ContentsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('contents')->delete();

        \DB::table('contents')->insert(array(
//            0 =>
//            array (
//                'content_id' => 1,
//                'content_name' => 'First meadia',
//                'file_mime_type' => 'image',
//                'file_name' => 'https://www.sample-videos.com/img/Sample-jpg-image-100kb.jpg',
//                'file_size' => 243,
//                'th_mime_type' => 'image',
//                'th_name' => 'https://www.sample-videos.com/img/Sample-jpg-image-100kb.jpg',
//                'th_size' => 20,
//                'copyright' => 0,
//                'private_content' => 0,
//                'availability_date' => NULL,
//                'expiration_date' => NULL,
//                'notes' => ' on a paid subscription basis.',
//                'created_at' => NULL,
//                'updated_at' => NULL,
//                'created_by' => 0,
//                'updated_by' => 0,
//            ),
//            1 =>
//            array (
//                'content_id' => 2,
//                'content_name' => 'Second meadia',
//                'file_mime_type' => 'video',
//                'file_name' => 'https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_1mb.mp4',
//                'file_size' => NULL,
//                'th_mime_type' => 'image',
//                'th_name' => 'https://www.sample-videos.com/img/Sample-jpg-image-100kb.jpg',
//                'th_size' => NULL,
//                'copyright' => 1,
//                'private_content' => 0,
//                'availability_date' => NULL,
//                'expiration_date' => NULL,
//                'notes' => 'Amazon Web Services is a subsidiary of Amazon.com that provides on-demand cloud computing platforms to individuals, companies and governments, on a paid subscription basis. ',
//                'created_at' => NULL,
//                'updated_at' => NULL,
//                'created_by' => 0,
//                'updated_by' => 0,
//            ),
//            2 =>
//            array (
//                'content_id' => 3,
//                'content_name' => 'Third meadia',
//                'file_mime_type' => 'video',
//                'file_name' => 'https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_1mb.mp4',
//                'file_size' => NULL,
//                'th_mime_type' => 'image',
//                'th_name' => 'https://www.sample-videos.com/img/Sample-jpg-image-100kb.jpg',
//                'th_size' => NULL,
//                'copyright' => 0,
//                'private_content' => 0,
//                'availability_date' => NULL,
//                'expiration_date' => NULL,
//                'notes' => ' on a paid subscription basis.',
//                'created_at' => NULL,
//                'updated_at' => NULL,
//                'created_by' => 0,
//                'updated_by' => 0,
//            ),
//            3 =>
//            array (
//                'content_id' => 4,
//                'content_name' => 'Fourth meadia',
//                'file_mime_type' => 'image',
//                'file_name' => 'https://www.sample-videos.com/img/Sample-jpg-image-100kb.jpg',
//                'file_size' => NULL,
//                'th_mime_type' => 'image',
//                'th_name' => 'https://www.sample-videos.com/img/Sample-jpg-image-100kb.jpg',
//                'th_size' => NULL,
//                'copyright' => 1,
//                'private_content' => 0,
//                'availability_date' => NULL,
//                'expiration_date' => NULL,
//                'notes' => 'Amazon Web Services is a subsidiary of Amazon.com that provides on-demand cloud computing platforms to individuals, companies and governments, on a paid subscription basis. ',
//                'created_at' => NULL,
//                'updated_at' => NULL,
//                'created_by' => 0,
//                'updated_by' => 0,
//            ),
//            4 =>
//            array (
//                'content_id' => 5,
//                'content_name' => 'Five meadia',
//                'file_mime_type' => 'video',
//                'file_name' => 'https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_1mb.mp4',
//                'file_size' => NULL,
//                'th_mime_type' => 'image',
//                'th_name' => 'https://www.sample-videos.com/img/Sample-jpg-image-100kb.jpg',
//                'th_size' => NULL,
//                'copyright' => 0,
//                'private_content' => 0,
//                'availability_date' => NULL,
//                'expiration_date' => NULL,
//                'notes' => ' on a paid subscription basis.',
//                'created_at' => NULL,
//                'updated_at' => NULL,
//                'created_by' => 0,
//                'updated_by' => 0,
//            ),
//            5 =>
//            array (
//                'content_id' => 6,
//                'content_name' => 'six meadia',
//                'file_mime_type' => 'video',
//                'file_name' => 'https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_1mb.mp4',
//                'file_size' => NULL,
//                'th_mime_type' => 'image',
//                'th_name' => 'https://www.sample-videos.com/img/Sample-jpg-image-100kb.jpg',
//                'th_size' => NULL,
//                'copyright' => 1,
//                'private_content' => 0,
//                'availability_date' => NULL,
//                'expiration_date' => NULL,
//                'notes' => 'Amazon Web Services is a subsidiary of Amazon.com that provides on-demand cloud computing platforms to individuals, companies and governments, on a paid subscription basis. ',
//                'created_at' => NULL,
//                'updated_at' => NULL,
//                'created_by' => 0,
//                'updated_by' => 0,
//            ),
//            6 =>
//            array (
//                'content_id' => 7,
//                'content_name' => 'seven meadia',
//                'file_mime_type' => 'video',
//                'file_name' => 'https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_1mb.mp4',
//                'file_size' => NULL,
//                'th_mime_type' => 'image',
//                'th_name' => 'https://www.sample-videos.com/img/Sample-jpg-image-100kb.jpg',
//                'th_size' => NULL,
//                'copyright' => 1,
//                'private_content' => 0,
//                'availability_date' => NULL,
//                'expiration_date' => NULL,
//                'notes' => 'Amazon Web Services is a subsidiary of Amazon.com that provides on-demand cloud computing platforms to individuals, companies and governments, on a paid subscription basis. ',
//                'created_at' => NULL,
//                'updated_at' => NULL,
//                'created_by' => 0,
//                'updated_by' => 0,
//            ),
//            7 =>
//            array (
//                'content_id' => 8,
//                'content_name' => 'eight meadia',
//                'file_mime_type' => 'video',
//                'file_name' => 'https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_1mb.mp4',
//                'file_size' => NULL,
//                'th_mime_type' => 'image',
//                'th_name' => 'https://www.sample-videos.com/img/Sample-jpg-image-100kb.jpg',
//                'th_size' => NULL,
//                'copyright' => 1,
//                'private_content' => 0,
//                'availability_date' => NULL,
//                'expiration_date' => NULL,
//                'notes' => 'Amazon Web Services is a subsidiary of Amazon.com that provides on-demand cloud computing platforms to individuals, companies and governments, on a paid subscription basis. ',
//                'created_at' => NULL,
//                'updated_at' => NULL,
//                'created_by' => 0,
//                'updated_by' => 0,
//            ),
//            8 =>
//            array (
//                'content_id' => 9,
//                'content_name' => 'eight meadia',
//                'file_mime_type' => 'video',
//                'file_name' => 'https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_1mb.mp4',
//                'file_size' => NULL,
//                'th_mime_type' => 'image',
//                'th_name' => 'https://www.sample-videos.com/img/Sample-jpg-image-100kb.jpg',
//                'th_size' => NULL,
//                'copyright' => 1,
//                'private_content' => 0,
//                'availability_date' => NULL,
//                'expiration_date' => NULL,
//                'notes' => 'Amazon Web Services is a subsidiary of Amazon.com that provides on-demand cloud computing platforms to individuals, companies and governments, on a paid subscription basis. ',
//                'created_at' => NULL,
//                'updated_at' => NULL,
//                'created_by' => 0,
//                'updated_by' => 0,
//            ),
            '0' => Array
            (
                'content_id' => 1,
                'content_name' => '3029 GALAXY NEW COLLECTION OOH 6X3 MASTER IT',
                'file_mime_type' => 'application/zip',
                'file_name' => '3029_GALAXY_NEW COLLECTION_OOH_6X3_MASTER_IT.zip',
                'file_size' => 553453981,
                'th_mime_type' => 'image/jpeg',
                'th_name' => '3029_GALAXY_NEW COLLECTION_OOH_6X3_MASTER_IT.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '1' => Array
            (
                'content_id' => 2,
                'content_name' => '3029 GALAXY NEW COLLECTION PRINT SP A4 MASTER IT',
                'file_mime_type' => 'application/zip',
                'file_name' => '3029_GALAXY_NEW COLLECTION_PRINT_SP_A4_MASTER_IT.zip',
                'file_size' => 98199414,
                'th_mime_type' => 'image/jpeg',
                'th_name' => '3029_GALAXY_NEW COLLECTION_PRINT_SP_A4_MASTER_IT.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '2' => Array
            (
                'content_id' => 3,
                'content_name' => '3032 KENDO NEW COLLECTION OOH 6X3 MASTER_IT',
                'file_mime_type' => 'application/zip',
                'file_name' => '3032_KENDO_NEW COLLECTION_OOH_6X3_MASTER_IT.zip',
                'file_size' => 79138743,
                'th_mime_type' => 'image/jpeg',
                'th_name' => '3032_KENDO_NEW COLLECTION_OOH_6X3_MASTER_IT.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '3' => Array
            (
                'content_id' => 4,
                'content_name' => '3032 KENDO NEW COLLECTION PRINT SP A4 MASTER IT',
                'file_mime_type' => 'application/zip',
                'file_name' => '3032_KENDO_NEW COLLECTION_PRINT_SP_A4_MASTER_IT.zip',
                'file_size' => 84494316,
                'th_mime_type' => 'image/jpeg',
                'th_name' => '3032_KENDO_NEW COLLECTION_PRINT_SP_A4_MASTER_IT.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '4' => Array
            (
                'content_id' => 5,
                'content_name' => '3039 MELPOT NEW COLLECTION OOH 6X3 MASTER IT',
                'file_mime_type' => 'application/zip',
                'file_name' => '3039_MELPOT_NEW COLLECTION_OOH_6X3_MASTER_IT.zip',
                'file_size' => 93803100,
                'th_mime_type' => 'image/jpeg',
                'th_name' => '3039_MELPOT_NEW COLLECTION_OOH_6X3_MASTER_IT.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '5' => Array
            (
                'content_id' => 6,
                'content_name' => '3039 MELPOT NEW COLLECTION PRINT SP A4 MASTER IT',
                'file_mime_type' => 'application/zip',
                'file_name' => '3039_MELPOT_NEW COLLECTION_PRINT_SP_A4_MASTER_IT.zip',
                'file_size' => 96119778,
                'th_mime_type' => 'image/jpeg',
                'th_name' => '3039_MELPOT_NEW COLLECTION_PRINT_SP_A4_MASTER_IT.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '6' => Array
            (
                'content_id' => 7,
                'content_name' => '3039 MELPOT NEW COLLECTION PRINT SP A4 NL NL',
                'file_mime_type' => 'application/zip',
                'file_name' => '3039_MELPOT_NEW COLLECTION_PRINT_SP_A4_NL_NL.zip',
                'file_size' => 94012681,
                'th_mime_type' => 'image/jpeg',
                'th_name' => '3039_MELPOT_NEW COLLECTION_PRINT_SP_A4_NL_NL.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 1,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '7' => Array
            (
                'content_id' => 8,
                'content_name' => 'B619 SAGGEZZA COMFORTDAYS PRINT DP A3 MASTER BE',
                'file_mime_type' => 'application/zip',
                'file_name' => 'B619_SAGGEZZA_COMFORTDAYS_PRINT_DP_A3_MASTER_BE.zip',
                'file_size' => 236400635,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'B619_SAGGEZZA_COMFORTDAYS_PRINT_DP_A3_MASTER_BE.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '8' => Array
            (
                'content_id' => 9,
                'content_name' => 'B619 SAGGEZZA COMFORTDAYS PRINT SP A4 MASTER BE',
                'file_mime_type' => 'application/zip',
                'file_name' => 'B619_SAGGEZZA_COMFORTDAYS_PRINT_SP_A4_MASTER_BE.zip',
                'file_size' => 237527555,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'B619_SAGGEZZA_COMFORTDAYS_PRINT_SP_A4_MASTER_BE.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '9' => Array
            (
                'content_id' => 10,
                'content_name' => 'B619 SAGGEZZA JOURSDUCONFORT PRINT DP A3 MASTER FR',
                'file_mime_type' => 'application/zip',
                'file_name' => 'B619_SAGGEZZA_JOURSDUCONFORT_PRINT_DP_A3_MASTER_FR.zip',
                'file_size' => 236185645,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'B619_SAGGEZZA_JOURSDUCONFORT_PRINT_DP_A3_MASTER_FR.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '10' => Array
            (
                'content_id' => 11,
                'content_name' => 'B619 SAGGEZZA JOURSDUCONFORT PRINT SP A4 MASTER FR',
                'file_mime_type' => 'application/zip',
                'file_name' => 'B619_SAGGEZZA_JOURSDUCONFORT_PRINT_SP_A4_MASTER_FR.zip',
                'file_size' => 235424013,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'B619_SAGGEZZA_JOURSDUCONFORT_PRINT_SP_A4_MASTER_FR.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '11' => Array
            (
                'content_id' => 12,
                'content_name' => 'C006 ADRENALINA COMFORTDAYS PRINT DP A3 MASTER BE',
                'file_mime_type' => 'application/zip',
                'file_name' => 'C006_ADRENALINA_COMFORTDAYS_PRINT_DP_A3_MASTER_BE.zip',
                'file_size' => 55527976,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'C006_ADRENALINA_COMFORTDAYS_PRINT_DP_A3_MASTER_BE.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '12' => Array
            (
                'content_id' => 13,
                'content_name' => 'C006 ADRENALINA COMFORTDAYS PRINT SP 143mmx218mm DEALER DEOLIFANT BE',
                'file_mime_type' => 'application/zip',
                'file_name' => 'C006_ADRENALINA_COMFORTDAYS_PRINT_SP_143mmx218mm_DEALER_DEOLIFANT_BE.zip',
                'file_size' => 18670278,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'C006_ADRENALINA_COMFORTDAYS_PRINT_SP_143mmx218mm_DEALER_DEOLIFANT_BE.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 1,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '13' => Array
            (
                'content_id' => 14,
                'content_name' => 'C006 ADRENALINA COMFORTDAYS PRINT SP A4 MASTER BE',
                'file_mime_type' => 'application/zip',
                'file_name' => 'C006_ADRENALINA_COMFORTDAYS_PRINT_SP_A4_MASTER_BE.zip',
                'file_size' => 52474563,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'C006_ADRENALINA_COMFORTDAYS_PRINT_SP_A4_MASTER_BE.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '14' => Array
            (
                'content_id' => 15,
                'content_name' => 'C006 ADRENALINA JOURSDUCONFORT PRINT DP A3 MASTER FR',
                'file_mime_type' => 'application/zip',
                'file_name' => 'C006_ADRENALINA_JOURSDUCONFORT_PRINT_DP_A3_MASTER_FR.zip',
                'file_size' => 55566202,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'C006_ADRENALINA_JOURSDUCONFORT_PRINT_DP_A3_MASTER_FR.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '15' => Array
            (
                'content_id' => 16,
                'content_name' => 'C006 ADRENALINA JOURSDUCONFORT PRINT SP A4 MASTER FR',
                'file_mime_type' => 'application/zip',
                'file_name' => 'C006_ADRENALINA_JOURSDUCONFORT_PRINT_SP_A4_MASTER_FR.zip',
                'file_size' => 52510081,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'C006_ADRENALINA_JOURSDUCONFORT_PRINT_SP_A4_MASTER_FR.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '16' => Array
            (
                'content_id' => 17,
                'content_name' => 'C074 TRIONFO COMFORTDAYS PRINT SP A4 DEALER STEVENS MEUBEL DEZONDAG BE',
                'file_mime_type' => 'application/zip',
                'file_name' => 'C074_TRIONFO_COMFORTDAYS_PRINT_SP_A4_DEALER_STEVENS_MEUBEL_DEZONDAG_BE.zip',
                'file_size' => 80841010,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'C074_TRIONFO_COMFORTDAYS_PRINT_SP_A4_DEALER_STEVENS_MEUBEL_DEZONDAG_BE.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 1,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '17' => Array
            (
                'content_id' => 18,
                'content_name' => 'GENERIC COMFORTDAYS POP TDISPLAY 340X250 MASTER BE',
                'file_mime_type' => 'application/zip',
                'file_name' => 'GENERIC_COMFORTDAYS_POP_TDISPLAY_340X250_MASTER_BE.zip',
                'file_size' => 549791,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'GENERIC_COMFORTDAYS_POP_TDISPLAY_340X250_MASTER_BE.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '18' => Array
            (
                'content_id' => 19,
                'content_name' => 'GENERIC COMFORTDAYS POP TDISPLAY 340X250 MASTER FR',
                'file_mime_type' => 'application/zip',
                'file_name' => 'GENERIC_COMFORTDAYS_POP_TDISPLAY_340X250_MASTER_FR.zip',
                'file_size' => 480082,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'GENERIC_COMFORTDAYS_POP_TDISPLAY_340X250_MASTER_FR.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '19' => Array
            (
                'content_id' => 20,
                'content_name' => 'GENERIC COMFORTDAYS PRINT OWNFLYER DP DEALER GOVA BE',
                'file_mime_type' => 'application/zip',
                'file_name' => 'GENERIC_COMFORTDAYS_PRINT_OWNFLYER_DP_DEALER_GOVA_BE.zip',
                'file_size' => 411176336,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'GENERIC_COMFORTDAYS_PRINT_OWNFLYER_DP_DEALER_GOVA_BE.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 1,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '20' => Array
            (
                'content_id' => 21,
                'content_name' => 'GENERIC NEW COLLECTION POP HTAG 85X140 MASTER IT',
                'file_mime_type' => 'application/zip',
                'file_name' => 'GENERIC_NEW COLLECTION_POP_HTAG_85X140_MASTER_IT.zip',
                'file_size' => 7899573,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'GENERIC_NEW COLLECTION_POP_HTAG_85X140_MASTER_IT.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '21' => Array
            (
                'content_id' => 22,
                'content_name' => 'GENERIC NEW COLLECTION POP HTAG 85X140 NL NL',
                'file_mime_type' => 'application/zip',
                'file_name' => 'GENERIC_NEW COLLECTION_POP_HTAG_85X140_NL_NL.zip',
                'file_size' => 6873685,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'GENERIC_NEW COLLECTION_POP_HTAG_85X140_NL_NL.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 1,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '22' => Array
            (
                'content_id' => 23,
                'content_name' => 'GENERIC NEW COLLECTION POP TDISPLAY 146X208 MASTER IT',
                'file_mime_type' => 'application/zip',
                'file_name' => 'GENERIC_NEW COLLECTION_POP_TDISPLAY_146X208_MASTER_IT.zip',
                'file_size' => 8044795,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'GENERIC_NEW COLLECTION_POP_TDISPLAY_146X208_MASTER_IT.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '23' => Array
            (
                'content_id' => 24,
                'content_name' => 'GENERIC NEW COLLECTION POP TDISPLAY A4 NL NL',
                'file_mime_type' => 'application/zip',
                'file_name' => 'GENERIC_NEW COLLECTION_POP_TDISPLAY_A4_NL_NL.zip',
                'file_size' => 6921341,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'GENERIC_NEW COLLECTION_POP_TDISPLAY_A4_NL_NL.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 1,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '24' => Array
            (
                'content_id' => 25,
                'content_name' => 'GENERIC NEW COLLECTION POP WDECAL DEALER COMO IT',
                'file_mime_type' => 'application/zip',
                'file_name' => 'GENERIC_NEW COLLECTION_POP_WDECAL_DEALER_COMO_IT.zip',
                'file_size' => 39382847,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'GENERIC_NEW COLLECTION_POP_WDECAL_DEALER_COMO_IT.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 1,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '25' => Array
            (
                'content_id' => 26,
                'content_name' => 'GENERIC NEW COLLECTION POP WDECAL DEALER EINDHOVEN NL',
                'file_mime_type' => 'application/zip',
                'file_name' => 'GENERIC_NEW COLLECTION_POP_WDECAL_DEALER_EINDHOVEN_NL.zip',
                'file_size' => 13760122,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'GENERIC_NEW COLLECTION_POP_WDECAL_DEALER_EINDHOVEN_NL.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 1,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '26' => Array
            (
                'content_id' => 27,
                'content_name' => 'GENERIC NEW COLLECTION POP WDECAL DEALER MILANO IT',
                'file_mime_type' => 'application/zip',
                'file_name' => 'GENERIC_NEW COLLECTION_POP_WDECAL_DEALER_MILANO_IT.zip',
                'file_size' => 34991692,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'GENERIC_NEW COLLECTION_POP_WDECAL_DEALER_MILANO_IT.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 1,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '27' => Array
            (
                'content_id' => 28,
                'content_name' => 'GENERIC NEW COLLECTION POP WDECAL DEALER ROMA IT',
                'file_mime_type' => 'application/zip',
                'file_name' => 'GENERIC_NEW COLLECTION_POP_WDECAL_DEALER_ROMA_IT.zip',
                'file_size' => 25547189,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'GENERIC_NEW COLLECTION_POP_WDECAL_DEALER_ROMA_IT.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 1,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '28' => Array
            (
                'content_id' => 29,
                'content_name' => 'GENERIC NEW COLLECTION POP WDECAL MASTER IT',
                'file_mime_type' => 'application/zip',
                'file_name' => 'GENERIC_NEW COLLECTION_POP_WDECAL_MASTER_IT.zip',
                'file_size' => 31604554,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'GENERIC_NEW COLLECTION_POP_WDECAL_MASTER_IT.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '29' => Array
            (
                'content_id' => 30,
                'content_name' => 'GENERIC SUMMERSALE POP TDISPLAY 340x245 MASTER BE',
                'file_mime_type' => 'application/zip',
                'file_name' => 'GENERIC_SUMMERSALE_POP_TDISPLAY_340x245_MASTER_BE.zip',
                'file_size' => 396905,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'GENERIC_SUMMERSALE_POP_TDISPLAY_340x245_MASTER_BE.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '30' => Array
            (
                'content_id' => 31,
                'content_name' => 'GENERIC SUMMERSALE POP TDISPLAY 340x245 MASTER FR',
                'file_mime_type' => 'application/zip',
                'file_name' => 'GENERIC_SUMMERSALE_POP_TDISPLAY_340x245_MASTER_FR.zip',
                'file_size' => 368039,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'GENERIC_SUMMERSALE_POP_TDISPLAY_340x245_MASTER_FR.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '31' => Array
            (
                'content_id' => 32,
                'content_name' => '2957 PHILO BRANDING PRINT DPS A3 MASTER EN',
                'file_mime_type' => 'application/zip',
                'file_name' => '2957_PHILO_BRANDING_PRINT_DPS_A3_MASTER_EN.zip',
                'file_size' => 283276541,
                'th_mime_type' => 'image/jpeg',
                'th_name' => '2957_PHILO_BRANDING_PRINT_DPS_A3_MASTER_EN.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '32' => Array
            (
                'content_id' => 33,
                'content_name' => '2987 JEREMY BRANDING PRINT DPS A3 MASTER EN',
                'file_mime_type' => 'application/zip',
                'file_name' => '2987_JEREMY_BRANDING_PRINT_DPS_A3_MASTER_EN.zip',
                'file_size' => 322555212,
                'th_mime_type' => 'image/jpeg',
                'th_name' => '2987_JEREMY_BRANDING_PRINT_DPS_A3_MASTER_EN.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '33' => Array
            (
                'content_id' => 34,
                'content_name' => '2994 IDO BRANDING PRINT DPS A3 MASTER EN',
                'file_mime_type' => 'application/zip',
                'file_name' => '2994_IDO_BRANDING_PRINT_DPS_A3_MASTER_EN.zip',
                'file_size' => 329577706,
                'th_mime_type' => 'image/jpeg',
                'th_name' => '2994_IDO_BRANDING_PRINT_DPS_A3_MASTER_EN.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '34' => Array
            (
                'content_id' => 35,
                'content_name' => '3000 LA SCALA BRANDING PRINT DPS A3 MASTER EN',
                'file_mime_type' => 'application/zip',
                'file_name' => '3000_LA SCALA_BRANDING_PRINT_DPS_A3_MASTER_EN.zip',
                'file_size' => 257394244,
                'th_mime_type' => 'image/jpeg',
                'th_name' => '3000_LA SCALA_BRANDING_PRINT_DPS_A3_MASTER_EN.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '35' => Array
            (
                'content_id' => 36,
                'content_name' => 'V981 HERMAN BRANDING PRINT DPS A3 MASTER EN',
                'file_mime_type' => 'application/zip',
                'file_name' => 'V981_HERMAN_BRANDING_PRINT_DPS_A3_MASTER_EN.zip',
                'file_size' => 244238671,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'V981_HERMAN_BRANDING_PRINT_DPS_A3_MASTER_EN.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '36' => Array
            (
                'content_id' => 37,
                'content_name' => 'B993 Talento Generale Correzione',
                'file_mime_type' => 'image/tiff',
                'file_name' => 'B993_Talento Generale Correzione.tif',
                'file_size' => 40537124,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'B993_Talento Generale Correzione.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '37' => Array
            (
                'content_id' => 38,
                'content_name' => 'C006 ADRENALINA NOPEOPLE',
                'file_mime_type' => 'image/tiff',
                'file_name' => 'C006_ADRENALINA_NOPEOPLE.tif',
                'file_size' => 17171716,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'C006_ADRENALINA_NOPEOPLE.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '38' => Array
            (
                'content_id' => 39,
                'content_name' => 'C006 ADRENALINA people',
                'file_mime_type' => 'image/tiff',
                'file_name' => 'C006_ADRENALINA_people.tif',
                'file_size' => 17571136,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'C006_ADRENALINA_people.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '39' => Array
            (
                'content_id' => 40,
                'content_name' => 'C008 FASCINO CLOSED',
                'file_mime_type' => 'image/tiff',
                'file_name' => 'C008_FASCINO_CLOSED.tif',
                'file_size' => 70636532,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'C008_FASCINO_CLOSED.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '40' => Array
            (
                'content_id' => 41,
                'content_name' => 'C008 FASCINO LETTO',
                'file_mime_type' => 'image/tiff',
                'file_name' => 'C008_FASCINO_LETTO.tif',
                'file_size' => 70584516,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'C008_FASCINO_LETTO.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '41' => Array
            (
                'content_id' => 42,
                'content_name' => 'C009 QUIETE NOPEOPLE',
                'file_mime_type' => 'image/tiff',
                'file_name' => 'C009_QUIETE_NOPEOPLE.tif',
                'file_size' => 13667104,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'C009_QUIETE_NOPEOPLE.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '42' => Array
            (
                'content_id' => 43,
                'content_name' => 'C009 QUIETE PEOPLE',
                'file_mime_type' => 'image/tiff',
                'file_name' => 'C009_QUIETE_PEOPLE.tif',
                'file_size' => 13329348,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'C009_QUIETE_PEOPLE.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '43' => Array
            (
                'content_id' => 44,
                'content_name' => 'C027 STUPORE',
                'file_mime_type' => 'image/tiff',
                'file_name' => 'C027_STUPORE.tif',
                'file_size' => 70586480,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'C027_STUPORE.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '44' => Array
            (
                'content_id' => 45,
                'content_name' => 'C037 Estasi Generale',
                'file_mime_type' => 'image/tiff',
                'file_name' => 'C037_Estasi Generale.tif',
                'file_size' => 35317472,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'C037_Estasi Generale.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '45' => Array
            (
                'content_id' => 46,
                'content_name' => 'C068 ASTUZIA NOPEOPLE',
                'file_mime_type' => 'image/tiff',
                'file_name' => 'C068_ASTUZIA_NOPEOPLE.tif',
                'file_size' => 69998000,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'C068_ASTUZIA_NOPEOPLE.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '46' => Array
            (
                'content_id' => 47,
                'content_name' => 'C068 ASTUZIA people',
                'file_mime_type' => 'image/tiff',
                'file_name' => 'C068_ASTUZIA_people.tif',
                'file_size' => 71031156,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'C068_ASTUZIA_people.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '47' => Array
            (
                'content_id' => 48,
                'content_name' => 'C071 CARISMA NOPEOPLE',
                'file_mime_type' => 'image/tiff',
                'file_name' => 'C071_CARISMA_NOPEOPLE.tif',
                'file_size' => 68154988,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'C071_CARISMA_NOPEOPLE.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '48' => Array
            (
                'content_id' => 49,
                'content_name' => 'C071 CARISMA PEOPLE',
                'file_mime_type' => 'image/tiff',
                'file_name' => 'C071_CARISMA_PEOPLE.tif',
                'file_size' => 70913260,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'C071_CARISMA_PEOPLE.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '49' => Array
            (
                'content_id' => 50,
                'content_name' => 'C074 TRIONFO NOPEOPLE',
                'file_mime_type' => 'image/tiff',
                'file_name' => 'C074_TRIONFO_NOPEOPLE.tif',
                'file_size' => 480205544,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'C074_TRIONFO_NOPEOPLE.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '50' => Array
            (
                'content_id' => 51,
                'content_name' => 'C074 TRIONFO PEOPLE',
                'file_mime_type' => 'image/tiff',
                'file_name' => 'C074_TRIONFO_PEOPLE.tif',
                'file_size' => 133668984,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'C074_TRIONFO_PEOPLE.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '51' => Array
            (
                'content_id' => 52,
                'content_name' => 'C074 TRIONFO VIDEO CUBICOMFORT',
                'file_mime_type' => 'video/mp4',
                'file_name' => 'C074_TRIONFO_VIDEO_CUBICOMFORT.mp4',
                'file_size' => 46091811,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'C074_TRIONFO_VIDEO_CUBICOMFORT.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '52' => Array
            (
                'content_id' => 53,
                'content_name' => 'C094 LEALE GEN',
                'file_mime_type' => 'image/tiff',
                'file_name' => 'C094_LEALE_GEN.tif',
                'file_size' => 35317912,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'C094_LEALE_GEN.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '53' => Array
            (
                'content_id' => 54,
                'content_name' => 'C107 Curioso Generale',
                'file_mime_type' => 'image/tiff',
                'file_name' => 'C107_Curioso Generale.tif',
                'file_size' => 70585756,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'C107_Curioso Generale.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '54' => Array
            (
                'content_id' => 55,
                'content_name' => 'corporateEDITIONS 308',
                'file_mime_type' => 'video/mp4',
                'file_name' => 'corporateEDITIONS_308.mp4',
                'file_size' => 540164544,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'corporateEDITIONS_308.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '55' => Array
            (
                'content_id' => 56,
                'content_name' => 'ACCOGLIENTE',
                'file_mime_type' => 'video/mp4',
                'file_name' => 'ACCOGLIENTE.mp4',
                'file_size' => 10114147,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'ACCOGLIENTE.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '56' => Array
            (
                'content_id' => 57,
                'content_name' => 'CURIOSO',
                'file_mime_type' => 'video/mp4',
                'file_name' => 'CURIOSO.mp4',
                'file_size' => 9858199,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'CURIOSO.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '57' => Array
            (
                'content_id' => 58,
                'content_name' => 'GIOVIALE',
                'file_mime_type' => 'video/mp4',
                'file_name' => 'GIOVIALE.mp4',
                'file_size' => 9946359,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'GIOVIALE.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '58' => Array
            (
                'content_id' => 59,
                'content_name' => 'GIULIVO',
                'file_mime_type' => 'video/mp4',
                'file_name' => 'GIULIVO.mp4',
                'file_size' => 10003025,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'GIULIVO.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '59' => Array
            (
                'content_id' => 60,
                'content_name' => 'ISPIRAZIONE',
                'file_mime_type' => 'video/mp4',
                'file_name' => 'ISPIRAZIONE.mp4',
                'file_size' => 10622653,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'ISPIRAZIONE.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '60' => Array
            (
                'content_id' => 61,
                'content_name' => 'SCALTRO',
                'file_mime_type' => 'video/mp4',
                'file_name' => 'SCALTRO.mp4',
                'file_size' => 10032816,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'SCALTRO.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '61' => Array
            (
                'content_id' => 62,
                'content_name' => 'TRANQUILLITA',
                'file_mime_type' => 'video/mp4',
                'file_name' => 'TRANQUILLITA.mp4',
                'file_size' => 10084381,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'TRANQUILLITA.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '62' => Array
            (
                'content_id' => 63,
                'content_name' => '1-10 Melpot vertical',
                'file_mime_type' => 'video/mp4',
                'file_name' => '1-10_Melpot_vertical.mp4',
                'file_size' => 12905800,
                'th_mime_type' => 'image/jpeg',
                'th_name' => '1-10_Melpot_vertical.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '63' => Array
            (
                'content_id' => 64,
                'content_name' => '1-10 Mentore',
                'file_mime_type' => 'video/mp4',
                'file_name' => '1-10_Mentore.mp4',
                'file_size' => 13081529,
                'th_mime_type' => 'image/jpeg',
                'th_name' => '1-10_Mentore.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '64' => Array
            (
                'content_id' => 65,
                'content_name' => '2-10 Crate',
                'file_mime_type' => 'video/mp4',
                'file_name' => '2-10_Crate.mp4',
                'file_size' => 3051018,
                'th_mime_type' => 'image/jpeg',
                'th_name' => '2-10_Crate.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '65' => Array
            (
                'content_id' => 66,
                'content_name' => '2-10 Icon vertical',
                'file_mime_type' => 'video/mp4',
                'file_name' => '2-10_Icon_vertical.mp4',
                'file_size' => 12943750,
                'th_mime_type' => 'image/jpeg',
                'th_name' => '2-10_Icon_vertical.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '66' => Array
            (
                'content_id' => 67,
                'content_name' => '3-10 Colosseo',
                'file_mime_type' => 'image/jpeg',
                'file_name' => '3-10_Colosseo.jpg',
                'file_size' => 1603603,
                'th_mime_type' => 'image/jpeg',
                'th_name' => '3-10_Colosseo.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '67' => Array
            (
                'content_id' => 68,
                'content_name' => '3-10 Stan vertical',
                'file_mime_type' => 'video/mp4',
                'file_name' => '3-10_Stan_vertical.mp4',
                'file_size' => 12974544,
                'th_mime_type' => 'image/jpeg',
                'th_name' => '3-10_Stan_vertical.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '68' => Array
            (
                'content_id' => 69,
                'content_name' => '4-10 Colosseo vertical',
                'file_mime_type' => 'video/mp4',
                'file_name' => '4-10_Colosseo_vertical.mp4',
                'file_size' => 12965987,
                'th_mime_type' => 'image/jpeg',
                'th_name' => '4-10_Colosseo_vertical.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '69' => Array
            (
                'content_id' => 70,
                'content_name' => '4-10 Icon',
                'file_mime_type' => 'video/mp4',
                'file_name' => '4-10_Icon.mp4',
                'file_size' => 13288701,
                'th_mime_type' => 'image/jpeg',
                'th_name' => '4-10_Icon.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '70' => Array
            (
                'content_id' => 71,
                'content_name' => 'Corporate2017 discodivendita sub EN',
                'file_mime_type' => 'video/mp4',
                'file_name' => 'Corporate2017_discodivendita_sub_EN.mp4',
                'file_size' => 923725038,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'poster.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '71' => Array
            (
                'content_id' => 72,
                'content_name' => 'MakingOfSalone wanders+bellinil sub EN',
                'file_mime_type' => 'video/mp4',
                'file_name' => 'MakingOfSalone_wanders+bellinil_sub_EN.mp4',
                'file_size' => 553156007,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'poster.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '72' => Array
            (
                'content_id' => 73,
                'content_name' => 'IAGO dsales',
                'file_mime_type' => 'video/mp4',
                'file_name' => 'IAGO_dsales.mp4',
                'file_size' => 32026253,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'poster.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '73' => Array
            (
                'content_id' => 74,
                'content_name' => 'PHILO dsales',
                'file_mime_type' => 'video/mp4',
                'file_name' => 'PHILO_dsales.mp4',
                'file_size' => 33174396,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'poster.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '74' => Array
            (
                'content_id' => 75,
                'content_name' => 'Australia SummerSale Stan30s',
                'file_mime_type' => 'video/mp4',
                'file_name' => 'Australia_SummerSale_Stan30s.mp4',
                'file_size' => 57102535,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'poster.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '75' => Array
            (
                'content_id' => 76,
                'content_name' => 'TV svizzera newcollection Galaxy',
                'file_mime_type' => 'video/quicktime',
                'file_name' => 'TV_svizzera_newcollection_Galaxy.mov',
                'file_size' => 191409044,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'poster.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '76' => Array
            (
                'content_id' => 77,
                'content_name' => '3035 STAN SUMMERSALE OOH 6X3 MASTER EN ',
                'file_mime_type' => 'video/mp4',
                'file_name' => '3035_STAN_SUMMERSALE_OOH_6X3_MASTER_EN.zip',
                'file_size' => 165136324,
                'th_mime_type' => 'image/jpeg',
                'th_name' => '3035_STAN_SUMMERSALE_OOH_6X3_MASTER_EN.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '77' => Array
            (
                'content_id' => 78,
                'content_name' => '3035 STAN SUMMERSALE PRINT SP A3 MASTER EN ',
                'file_mime_type' => 'video/mp4',
                'file_name' => '3035_STAN_SUMMERSALE_PRINT_SP_A3_MASTER_EN.zip',
                'file_size' => 165875398,
                'th_mime_type' => 'image/jpeg',
                'th_name' => '3035_STAN_SUMMERSALE_PRINT_SP_A3_MASTER_EN.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '78' => Array
            (
                'content_id' => 79,
                'content_name' => '3035 STAN SUMMERSALE PRINT SP A3 MASTER PEOPLE EN ',
                'file_mime_type' => 'video/mp4',
                'file_name' => '3035_STAN_SUMMERSALE_PRINT_SP_A3_MASTER_PEOPLE_EN.zip',
                'file_size' => 28490904,
                'th_mime_type' => 'image/jpeg',
                'th_name' => '3035_STAN_SUMMERSALE_PRINT_SP_A3_MASTER_PEOPLE_EN.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '79' => Array
            (
                'content_id' => 80,
                'content_name' => '3035 STAN SUMMERSALE PRINT SP A4 MASTER EN ',
                'file_mime_type' => 'video/mp4',
                'file_name' => '3035_STAN_SUMMERSALE_PRINT_SP_A4_MASTER_EN.zip',
                'file_size' => 119472701,
                'th_mime_type' => 'image/jpeg',
                'th_name' => '3035_STAN_SUMMERSALE_PRINT_SP_A4_MASTER_EN.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '80' => Array
            (
                'content_id' => 81,
                'content_name' => '3035 STAN SUMMERSALE PRINT SP A4 MASTER PEOPLE EN ',
                'file_mime_type' => 'video/mp4',
                'file_name' => '3035_STAN_SUMMERSALE_PRINT_SP_A4_MASTER_PEOPLE_EN.zip',
                'file_size' => 104950153,
                'th_mime_type' => 'image/jpeg',
                'th_name' => '3035_STAN_SUMMERSALE_PRINT_SP_A4_MASTER_PEOPLE_EN.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '81' => Array
            (
                'content_id' => 82,
                'content_name' => 'GENERIC SUMMERSALE POP HTAG 85X140 MASTER EN',
                'file_mime_type' => 'video/mp4',
                'file_name' => 'GENERIC_SUMMERSALE_POP_HTAG_85X140_MASTER_EN.zip',
                'file_size' => 6015206,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'GENERIC_SUMMERSALE_POP_HTAG_85X140_MASTER_EN.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '82' => Array
            (
                'content_id' => 83,
                'content_name' => 'GENERIC SUMMERSALE POP HTAG 90X158 MASTER EN',
                'file_mime_type' => 'video/mp4',
                'file_name' => 'GENERIC_SUMMERSALE_POP_HTAG_90X158_MASTER_EN.zip',
                'file_size' => 6107777,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'GENERIC_SUMMERSALE_POP_HTAG_90X158_MASTER_EN.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '83' => Array
            (
                'content_id' => 84,
                'content_name' => 'GENERIC SUMMERSALE POP HTAG A6 MASTER EN',
                'file_mime_type' => 'video/mp4',
                'file_name' => 'GENERIC_SUMMERSALE_POP_HTAG_A6_MASTER_EN.zip',
                'file_size' => 6238132,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'GENERIC_SUMMERSALE_POP_HTAG_A6_MASTER_EN.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '84' => Array
            (
                'content_id' => 85,
                'content_name' => 'GENERIC SUMMERSALE POP TDISPLAY 210X297 MASTER EN',
                'file_mime_type' => 'video/mp4',
                'file_name' => 'GENERIC_SUMMERSALE_POP_TDISPLAY_210X297_MASTER_EN.zip',
                'file_size' => 3397945,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'GENERIC_SUMMERSALE_POP_TDISPLAY_210X297_MASTER_EN.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '85' => Array
            (
                'content_id' => 86,
                'content_name' => 'GENERIC SUMMERSALE POP WDECAL 1800X1100 MASTER EN',
                'file_mime_type' => 'video/mp4',
                'file_name' => 'GENERIC_SUMMERSALE_POP_WDECAL_1800X1100_MASTER_EN.zip',
                'file_size' => 12259107,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'GENERIC_SUMMERSALE_POP_WDECAL_1800X1100_MASTER_EN.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

            '86' => Array
            (
                'content_id' => 87,
                'content_name' => 'GENERIC SUMMERSALE RADIOSPOT MASTER.EN ',
                'file_mime_type' => 'video/mp4',
                'file_name' => 'GENERIC_SUMMERSALE_RADIOSPOT_MASTER.EN.zip',
                'file_size' => 6101818,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'poster.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),
            '87' => Array
            (
                'content_id' => 88,
                'content_name' => 'Modello 2422 Anteprima ',
                'file_mime_type' => 'application/zip',
                'file_name' => 'model_2022.zip',
                'file_size' => 6101818,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'Anteprima.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),
            '88' => Array
            (
                'content_id' => 89,
                'content_name' => 'Modello2911 Long Beach',
                'file_mime_type' => 'application/zip',
                'file_name' => 'model_2911.zip',
                'file_size' => 6101818,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'Long_Beach.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),
            '89' => Array
            (
                'content_id' => 90,
                'content_name' => '1-10 mentore copy',
                'file_mime_type' => 'image/jpeg',
                'file_name' => '1-10_mentore_copy.jpg',
                'file_size' => 6101818,
                'th_mime_type' => 'image/jpeg',
                'th_name' => '1-10_mentore_copy.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),
            '90' => Array
            (
                'content_id' => 91,
                'content_name' => '2-10 crate copy',
                'file_mime_type' => 'image/jpeg',
                'file_name' => '2-10_crate_copy.jpg',
                'file_size' => 6101818,
                'th_mime_type' => 'image/jpeg',
                'th_name' => '2-10_crate_copy.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),
            '91' => Array
            (
                'content_id' => 92,
                'content_name' => '3-10 Colosseo copy',
                'file_mime_type' => 'image/jpeg',
                'file_name' => '3-10_Colosseo_copy.jpg',
                'file_size' => 6101818,
                'th_mime_type' => 'image/jpeg',
                'th_name' => '3-10_Colosseo_copy.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),
            '92' => Array
            (
                'content_id' => 93,
                'content_name' => '4-10 icon copy',
                'file_mime_type' => 'image/jpeg',
                'file_name' => '4-10_icon_copy.jpg',
                'file_size' => 6101818,
                'th_mime_type' => 'image/jpeg',
                'th_name' => '4-10_icon_copy.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),
            '93' => Array
            (
                'content_id' => 94,
                'content_name' => 'C074 TRIONFO INSTORE POP PRODUCT BROCHURE MASTER ENG',
                'file_mime_type' => 'application/pdf',
                'file_name' => 'C074_TRIONFO_INSTORE_POP_PRODUCT_BROCHURE_MASTER_ENG.pdf',
                'file_size' => 6101818,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'C074_TRIONFO_anteprima_jpg.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),
            '94' => Array
            (
                'content_id' => 95,
                'content_name' => 'C027 STUPORE INSTORE POP PRODUCT BROCHURE MASTER ENG',
                'file_mime_type' => 'application/pdf',
                'file_name' => 'C027_STUPORE_INSTORE_POP_PRODUCT_BROCHURE_MASTER_ENG.pdf',
                'file_size' => 6101818,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'C027_STUPORE_anteprima_jpg.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),
            '95' => Array
            (
                'content_id' => 96,
                'content_name' => 'C009 QUIETE INSTORE POP PRODUCT BROCHURE MASTER ENG',
                'file_mime_type' => 'application/pdf',
                'file_name' => 'C009_QUIETE_INSTORE_POP_PRODUCT_BROCHURE_MASTER_ENG.pdf',
                'file_size' => 6101818,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'C009_QUIETE_anteprima_jpg.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),
            '96' => Array
            (
                'content_id' => 97,
                'content_name' => 'B993 TALENTO NEWCOLLECTION PRINT DP MASTER ENG',
                'file_mime_type' => 'image/jpeg',
                'file_name' => 'B993_TALENTO_NEWCOLLECTION_PRINT_DP_MASTER_ENG.JPG',
                'file_size' => 6101818,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'B993_TALENTO_NEWCOLLECTION_PRINT_DP_anteprima.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),
            '97' => Array
            (
                'content_id' => 98,
                'content_name' => 'B993 TALENTO NEWCOLLECTION PRINT SP MASTER ENG',
                'file_mime_type' => 'image/jpeg',
                'file_name' => 'B993_TALENTO_NEWCOLLECTION_PRINT_SP_MASTER_ENG.JPG',
                'file_size' => 6101818,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'B993_TALENTO_NEWCOLLECTION_PRINT_SP_anteprima.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),
            '98' => Array
            (
                'content_id' => 99,
                'content_name' => 'C071 CARISMA WINTERSALE PRINT DP MASTER ENG',
                'file_mime_type' => 'image/jpeg',
                'file_name' => 'C071_CARISMA_WINTERSALE_PRINT_DP_MASTER_ENG.jpg',
                'file_size' => 6101818,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'C071_CARISMA_WINTERSALE_PRINT_DP_anteprima.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),
            '99' => Array
            (
                'content_id' => 100,
                'content_name' => 'C071 CARISMA WINTERSALE PRINT SP MASTER ENG',
                'file_mime_type' => 'image/jpeg',
                'file_name' => 'C071_CARISMA_WINTERSALE_PRINT_SP_MASTER_ENG.JPG',
                'file_size' => 6101818,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'C071_CARISMA_WINTERSALE_PRINT_SP_anteprima.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),
            '100' => Array
            (
                'content_id' => 101,
                'content_name' => 'C027 STUPORE COMFORTDAYS PRINT DP MASTER ENG',
                'file_mime_type' => 'image/jpeg',
                'file_name' => 'C027_STUPORE_COMFORTDAYS_PRINT_DP_MASTER_ENG.jpg',
                'file_size' => 6101818,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'C027_STUPORE_COMFORTDAYS_PRINT_DP_anteprima.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),
            '101' => Array
            (
                'content_id' => 102,
                'content_name' => 'C027 STUPORE COMFORTDAYS PRINT OOH 6x3 MASTER ENG',
                'file_mime_type' => 'image/jpeg',
                'file_name' => 'C027_STUPORE_COMFORTDAYS_PRINT_OOH_6x3_MASTER_ENG.jpg',
                'file_size' => 6101818,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'poster.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),
            '103' => Array
            (
                'content_id' => 103,
                'content_name' => 'C027 STUPORE COMFORTDAYS PRINT SP MASTER ENG',
                'file_mime_type' => 'image/jpeg',
                'file_name' => 'C027_STUPORE_COMFORTDAYS_PRINT_SP_MASTER_ENG.JPG',
                'file_size' => 6101818,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'C027_STUPORE_COMFORTDAYS_PRINT_SP_anteprima.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),
            '104' => Array
            (
                'content_id' => 104,
                'content_name' => 'B993 TALENTO NEWCOLLECTION PRINT OOH 6x3 MASTER ENG',
                'file_mime_type' => 'image/jpeg',
                'file_name' => 'B993_TALENTO_NEWCOLLECTION_PRINT_OOH_6x3_MASTER_ENG.jpg',
                'file_size' => 6101818,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'B993_TALENTO_NEWCOLLECTION_PRINT_OOH_6x3_anteprima.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),
            '105' => Array
            (
                'content_id' => 105,
                'content_name' => 'C027 STUPORE COMFORTDAYS PRINT OOH 6x3 MASTER ENG',
                'file_mime_type' => 'image/jpeg',
                'file_name' => 'C027_STUPORE_COMFORTDAYS_PRINT_OOH_6x3_MASTER_ENG.jpg',
                'file_size' => 6101818,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'C027_STUPORE_COMFORTDAYS_PRINT_OOH_6x3_anteprima.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),
            '106' => Array
            (
                'content_id' => 106,
                'content_name' => 'C071 CARISMA WINTERSALE PRINT OOH 6x3 MASTER ENG',
                'file_mime_type' => 'image/jpeg',
                'file_name' => 'C071_CARISMA_WINTERSALE_PRINT_OOH_6x3_MASTER_ENG.jpg',
                'file_size' => 6101818,
                'th_mime_type' => 'image/jpeg',
                'th_name' => 'C071_CARISMA_WINTERSALE_PRINT_OOH_6x3_anteprima.jpg',
                'th_size' => 0,
                'copyright' => 1,
                'private_content' => 0,
                'availability_date' => NULL,
                'expiration_date' => NULL,
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
            ),

        ));


    }
}